angular = require "angular"
translations = require "../i18n/locale-en.json"
require "@progress/kendo-ui/js/kendo.core.js"
require "../vendor_overrides/@progress/kendo-ui/js/kendo.angular.js"

require "../polyfills/"

angular.module("ThemisComponents", [
  require "angular-aria"
  require "angular-messages"
  require "angular-sanitize"
  require "angular-translate"
  require "angular-translate-loader-static-files"
  "kendo.directives"
  require "ui-select"
]).config ["$translateProvider", ($translateProvider) ->
    $translateProvider.translations "en", translations
      .preferredLanguage "en"
      .useSanitizeValueStrategy "sanitize"
]

require "./services/"
require "./thActionBar/"
require "./thActionBarBilling/"
require "./thAlert/"
require "./thAutocomplete/"
require "./thButton/"
require "./thCheckbox/"
require "./thCompile/"
require "./thContentHeader/"
require "./thContextualMessage/"
require "./thDataTable/"
require "./thDatePicker/"
require "./thDefaults/"
require "./thDisclosure/"
require "./thDropdown/"
require "./thError/"
require "./thFilter/"
require "./thGrid/"
require "./thInput/"
require "./thLazy/"
require "./thLoader/"
require "./thModal/"
require "./thPlural/"
require "./thPopover/"
require "./thPopoverLegacy/"
require "./thRadioGroup/"
require "./thScheduler/"
require "./thSelect/"
require "./thSwitch/"
require "./thTable/"
require "./thTabset/"
require "./thTextarea/"
require "./thTimePicker/"
require "./thTruncate/"
require "./thViewModel/"
require "./thWithFocus/"
require "./thWithLabel/"
require "./thWithMessages/"

module.exports = "ThemisComponents"
