require './Array.find.polyfill'
require './Array.findIndex.polyfill'
require './Element.matches.polyfill'
require './jQuery.typeAttribute.patch'
require './Object.assign.polyfill'
require './scrollingElement.polyfill'
require './String.includes.polyfill'
