require './filters/'
require './thFilter.directive'
require './thCustomFilterRow.directive'
require './thCustomFilters.component'
require './thSearchRow.directive'
require './thStaticFilters.directive'
require './thCustomFilterConverter.service'
