require './filters/'
require './thFilter.directive'
require './thCustomFilterRow.directive'
require './thCustomFilters.directive'
require './thSearchRow.directive'
require './thStaticFilters.directive'
require './thCustomFilterConverter.service'
