require './thTable.directive'
require './thTableCell.directive'
require './thTableRow.directive'

require './thSimpleTableDelegate.service'
require './thTable.service'
require './thTableDelegate.service'
require './thTableHeader.service'
require './thTablePagination.service'
require './thTableSort.service'
